### ISSUE TITLE
Как этим пользоваться?

### ISSUE THREAD

**Issue by sooqua** [dimorinny/twitch-interesting-fragments#1]
Как запустить вашу программу? Не имел опыта с Golang раньше. Пытался так:
>set NICKNAME=***
>set OAUTH=oauth:***
>set CHANNEL=TwitchPresents
>%GOPATH%/bin/twitch-interesting-fragments.exe
2017/03/22 02:46:39 no reachable servers

**Comment by dimorinny** [comment]
Привет, данная ошибка связана с тем, что не передан хост монги. Я скоро напишу нормально ридми, пока вкрации поясню здесь:

Данный проект не автономен, он отвечает только за детектинг всплесков комментариев на стриме и дергает другой [микросервис](https://github.com/dimorinny/twitch-fragment-upload), который заливает данный фрагмент в группу ВК. Адрес данного сервиса передается через ENV.

Так же для функционирования данного сервиса нужна монга для сохранения метаданных видиофрагментов. Путь да нее так же передается через ENV.

Все параметры пока можно посмотреть [здесь](https://github.com/dimorinny/twitch-interesting-fragments/blob/master/configuration/configuration.go).

Я скоро опубликую репозиторий, который позволит запустить это все вместе с помощью Docker.

**Comment by sooqua** [comment]
Сегодня ровно месяц, как я жду новостей от вас 🙂
Я собирался написать подобную вещь на C#, но боюсь, что моих знаний может не хватить. А у вас, кажется, уже получилось. Не могли бы вы написать инструкцию, как это хотя бы запустить? Тогда я попробую изменить код под свои цели.

**Comment by dimorinny** [comment]
Братишка, прости. Я сегодня-завтра все напишу.

**Comment by sooqua** [comment]
Спасибо. 👍

**Comment by sooqua** [comment]
Я тем временем сделал скрипт для поиска интересных моментов в VOD`ах: https://github.com/sooqua/TwitchVODEnhancer

**Comment by khasanovbi** [comment]
@sooqua даже с четким Readme, красава)

**Comment by dimorinny** [comment]
@sooqua А што за VOD`ы? А то я не в курсе, что это такое

**Comment by sooqua** [comment]
Video on demand. Записи трансляций.
